<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws.proto

namespace WsProto\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WsProto.Block.BetData</code>
 */
class BetData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 user_num = 1;</code>
     */
    private $user_num;
    /**
     * Generated from protobuf field <code>repeated int32 bet_amount = 2;</code>
     */
    private $bet_amount;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $user_num
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $bet_amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ws::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 user_num = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserNum()
    {
        return $this->user_num;
    }

    /**
     * Generated from protobuf field <code>repeated int32 user_num = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserNum($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->user_num = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 bet_amount = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBetAmount()
    {
        return $this->bet_amount;
    }

    /**
     * Generated from protobuf field <code>repeated int32 bet_amount = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBetAmount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->bet_amount = $arr;

        return $this;
    }

}

