<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws.proto

namespace WsProto\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 握手
 *
 * Generated from protobuf message <code>WsProto.Block.HandShake</code>
 */
class HandShake extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string open_data = 1;</code>
     */
    protected $open_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $open_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ws::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string open_data = 1;</code>
     * @return string
     */
    public function getOpenData()
    {
        return $this->open_data;
    }

    /**
     * Generated from protobuf field <code>string open_data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenData($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_data = $var;

        return $this;
    }

}

