<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws.proto

namespace WsProto\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 心跳
 *
 * Generated from protobuf message <code>WsProto.Block.HeartBeat</code>
 */
class HeartBeat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ping = 1;</code>
     */
    protected $ping = '';
    /**
     * Generated from protobuf field <code>string pong = 2;</code>
     */
    protected $pong = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ping
     *     @type string $pong
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ws::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ping = 1;</code>
     * @return string
     */
    public function getPing()
    {
        return $this->ping;
    }

    /**
     * Generated from protobuf field <code>string ping = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPing($var)
    {
        GPBUtil::checkString($var, True);
        $this->ping = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pong = 2;</code>
     * @return string
     */
    public function getPong()
    {
        return $this->pong;
    }

    /**
     * Generated from protobuf field <code>string pong = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPong($var)
    {
        GPBUtil::checkString($var, True);
        $this->pong = $var;

        return $this;
    }

}

