<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws.proto

namespace WsProto\Block;

use UnexpectedValueException;

/**
 * Protobuf type <code>WsProto.Block.MessageId</code>
 */
class MessageId
{
    /**
     * Generated from protobuf enum <code>MSG_NONE = 0;</code>
     */
    const MSG_NONE = 0;
    /**
     * 心跳协议
     *
     * Generated from protobuf enum <code>MSG_HEARTBEAT = 1;</code>
     */
    const MSG_HEARTBEAT = 1;
    /**
     * 最近区块
     *
     * Generated from protobuf enum <code>MSG_LATEST_BLOCK = 102;</code>
     */
    const MSG_LATEST_BLOCK = 102;
    /**
     * 开奖结果
     *
     * Generated from protobuf enum <code>MSG_OPEN_RES = 103;</code>
     */
    const MSG_OPEN_RES = 103;
    /**
     * 房间下注数据
     *
     * Generated from protobuf enum <code>MSG_ROOM_BET_DATA = 104;</code>
     */
    const MSG_ROOM_BET_DATA = 104;
    /**
     * 房间用户下注数据
     *
     * Generated from protobuf enum <code>MSG_ROOM_USER_BET_DATA = 105;</code>
     */
    const MSG_ROOM_USER_BET_DATA = 105;
    /**
     * 异常消息
     *
     * Generated from protobuf enum <code>MSG_EXCEPTION_MSG = 500;</code>
     */
    const MSG_EXCEPTION_MSG = 500;

    private static $valueToName = [
        self::MSG_NONE => 'MSG_NONE',
        self::MSG_HEARTBEAT => 'MSG_HEARTBEAT',
        self::MSG_LATEST_BLOCK => 'MSG_LATEST_BLOCK',
        self::MSG_OPEN_RES => 'MSG_OPEN_RES',
        self::MSG_ROOM_BET_DATA => 'MSG_ROOM_BET_DATA',
        self::MSG_ROOM_USER_BET_DATA => 'MSG_ROOM_USER_BET_DATA',
        self::MSG_EXCEPTION_MSG => 'MSG_EXCEPTION_MSG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

