<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws.proto

namespace WsProto\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 房间用户下注数据
 *
 * Generated from protobuf message <code>WsProto.Block.RoomUserBetData</code>
 */
class RoomUserBetData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     */
    protected $game_id = '';
    /**
     * Generated from protobuf field <code>int32 bet_level = 2;</code>
     */
    protected $bet_level = 0;
    /**
     * Generated from protobuf field <code>int32 block_number = 3;</code>
     */
    protected $block_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $game_id
     *     @type int $bet_level
     *     @type int $block_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ws::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->game_id;
    }

    /**
     * Generated from protobuf field <code>string game_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkString($var, True);
        $this->game_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 bet_level = 2;</code>
     * @return int
     */
    public function getBetLevel()
    {
        return $this->bet_level;
    }

    /**
     * Generated from protobuf field <code>int32 bet_level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBetLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->bet_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 block_number = 3;</code>
     * @return int
     */
    public function getBlockNumber()
    {
        return $this->block_number;
    }

    /**
     * Generated from protobuf field <code>int32 block_number = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_number = $var;

        return $this;
    }

}

